services:
  sshport:
    build: .
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      # Host key is written by preStartCmd from SSH_HOST_KEY env var
      - ./.ssh:/app/.ssh:ro
